version: '3'

services:
  alpine-bats:
    build:
      context: .
      dockerfile: Dockerfile.alpine-bats
    image: djschaper/circleci-baseimages:bats-alpine3.7
  alpine-shellcheck:
    build:
      context: .
      dockerfile: Dockerfile.alpine-sc
    image: djschaper/circleci-baseimages:shellcheck-alpine3.7
  alpine-combined:
    build:
      context: .
      dockerfile: Dockerfile.alpine-combined
    image: djschaper/circleci-baseimages:combined-alpine3.7