FROM djschaper/shellcheck:alpine-latest as shellcheck

FROM alpine:3.7

COPY --from=shellcheck /bin/shellcheck /bin

RUN apk --no-cache --virtual .run-depends add \
      bash \
      curl \
      drill \
      git \
      openssh \
      openssl

ENTRYPOINT ["/bin/sh"]